# Generated by Django 2.1 on 2020-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=2000)),
                ('category', models.CharField(max_length=2000)),
                ('created_date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
    ]
